### ISSUE TITLE
Chart stlyes problem for rtl languages

### ISSUE THREAD

**Issue by amirrezashf** [toolstack/just-writing-statistics#3]
Hey there!
according to this link: https://wordpress.org/support/topic/chart-problem-for-rtl-languages/#post-17881916
We have a problem with Just Writing Statistics plugin
We’re using this plugin on our wordpress rtl website. But in wordpress dashboard we have a problem with Chart styles.
It’s need some improvements to fix.
Also in author charts, all of them are the same color!
I attached 2 screenshots.
<img width="1342" alt="Screenshot 1403-04-21 at 11 44 21" src="https://github.com/toolstack/just-writing-statistics/assets/43330890/ad1f32d8-06af-4152-a4ee-942f312f2e93">
<img width="1338" alt="Screenshot 1403-04-21 at 11 44 41" src="https://github.com/toolstack/just-writing-statistics/assets/43330890/8c20be1b-d895-41d0-9f67-55c2647a794a">

**Comment by toolstack** [comment]
The table issue should be easy to fix, assuming you mean the incorrect divider lines and not something else.

The second issues is probably "as designed", but I agree having multiple colours might be a good idea, not sure if it's possible or not based on the charting library.

**Comment by amirrezashf** [comment]
Thanks for the response & your answer!
So in your next updates for Just Writing Statistics plugin, we have to see these improvements.

**Comment by toolstack** [comment]
I've committed fixes for both items, will do a release on the weekend sometime.

**Comment by toolstack** [comment]
Release complete.

**Comment by amirrezashf** [comment]
Thank youuuu!
Thanks a lot!
